apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs
  resources:
    requests:
      storage: 10Gi
